FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y wget gnupg
RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN apt-get update
RUN apt-get install -y mongodb-org
RUN apt-get install cron -y

COPY ./mongo/cron-conf/crontab /var/spool/cron/crontabs/root

ENTRYPOINT ["sh", "-c", "service cron start && cat /var/spool/cron/crontabs/root | crontab - && tail -f /dev/null"]